title = "Welcome to my tech-blog"
baseURL = '/'
languageCode = 'en-us'
theme = "hugo-blog-awesome"


# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 50
  [[menu.main]]
    weight = 30
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 40
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    title = ""    

[params]
  sitename = "Martijn van Schie"
  defaultColor = "dark" # set default color mode: dark or light
  description = "A typical personal tech-blog"

[params.author]
  avatar = "img/avatar.jpg"
  intro = "Martijn van Schie"
  name = "Martijn van Schie"
  description = "A typical personal tech-blog"

# Author config
[author]
  name = "Martijn van Schie"
  email = "martijnvanschie@gmail.com"
  link = "https://google.com"  